const ADD_MESSAGE = 'ADD_MESSAGE';
const GET_MESSAGE = 'GET_MESSAGE';
const ADD_TEACHER = 'ADD_TEACHER';
const GET_TEACHER = 'GET_TEACHER';
const ADD_LIBRARY = 'ADD_LIBRARY';
const GET_LIBRARY = 'GET_LIBRARY';
const SET_OPENED_LIBRARY = 'SET_OPENED_LIBRARY';
const GET_REMINDER = 'GET_REMINDER';
const DISMISS_REMINDER = 'DISMISS_REMINDER';
const DISMISS_ALL_REMINDER = 'DISMISS_ALL_REMINDER';
const GET_SEMINAR = 'GET_SEMINAR';
const ADD_SEMINAR = 'ADD_SEMINAR';
const CHANGE_TAB = 'CHANGE_TAB';
const GET_TOKEN = 'GET_TOKEN';
const VERIFY_TOKEN = 'VERIFY_TOKEN';
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGIN_FAILURE = 'LOGIN_FAILURE';
const LOGOUT = 'LOGOUT';
const UPDATE_NAME = 'UPDATE_NAME';
const UPDATE_COLOR = 'UPDATE_COLOR';

export {
  ADD_MESSAGE, GET_MESSAGE, ADD_TEACHER, GET_TEACHER, ADD_LIBRARY, GET_LIBRARY,
  SET_OPENED_LIBRARY, GET_REMINDER, DISMISS_REMINDER, DISMISS_ALL_REMINDER,
  GET_SEMINAR, ADD_SEMINAR, CHANGE_TAB, GET_TOKEN, VERIFY_TOKEN, LOGIN_SUCCESS,
  LOGIN_FAILURE, LOGOUT, UPDATE_NAME, UPDATE_COLOR,
};
